### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by shiversoftdev** [ssnob/t7fastspend#1]
who

**Comment by ssnob** [comment]
ratio

**Comment by shiversoftdev** [comment]
counter ratio

**Comment by shiversoftdev** [comment]
https://images-ext-2.discordapp.net/external/iEPbM6qMENonLkHztJFawQhO0mFv6ltz7FIiRliOvTs/https/media.discordapp.net/attachments/859294501067161622/893591408856944660/output-onlinegiftools.gif

**Comment by ssnob** [comment]
https://media.discordapp.net/attachments/859332346259570699/894689958525288528/818413769226715158.png
